apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
      - name: postgre
        image: postgres:15.0
        startupProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 5
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "kubenews"
        - name: POSTGRES_USER
          value: "kubenews"
        - name: POSTGRES_PASSWORD
          value: "Pg#123"
        volumeMounts:
        - mountPath: /var/lib/pgsql/14/data/
          name: postgre
      volumes:
      - name: postgre
        persistentVolumeClaim:
          claimName: database-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  selector:
    app: postgre
  ports:
  - port: 5432
    targetPort: 5432
  type: NodePort
